### ISSUE TITLE
Doesn't work with previously saved files.

### ISSUE THREAD

**Issue by RyanMadsen** [ThioJoe/AHK-Scripts#16]
It appears to only work with Unsaved / new files. For example an already saved .txt file is opened in Notepad, I did "File" > "Save as", middle-clicked an empty area, pressed one of the path choices, and it asked if I wanted to replace the original file instead of going to the new place.

Maybe you mentioned this already somewhere in the video. I apologize if so.

**Comment by ThioJoe** [comment]
This _should_ be fixed with the latest v1.2.2
