### ISSUE TITLE
[Explorer Dialog Path Selector] Not working with "Scilab 2024.1.0" file open/save dialog windows

### ISSUE THREAD

**Issue by RCMaca** [ThioJoe/AHK-Scripts#20]
Explorer Dialog Path Selector does not appear to work with "Scilab 2024.1.0" file open/save dialog windows. 

Does not matter where the mouse button is middle clicked, there is no popup. 

Attached is a screenshot of the window style in case that helps.
![Screenshot 2024-11-17 102949](https://github.com/user-attachments/assets/d858f5b0-f655-4800-a025-a7f35288ff3f)

**Comment by rcmaehl** [comment]
Not sure if AHK has a "Window Spy" utility, but allowing users to specific custom controls to look for would resolve this (#20), part of #19, and #12

**Comment by ThioJoe** [comment]
Ok this should be fixed now as of v1.2.2. Turns out it was an entirely new type of window class built in java called "SunAwtDialog". It requires some special handling but it should work.

**Comment by RCMaca** [comment]
Confirmed fixed. Thank you very much for the rapid update!
