### ISSUE TITLE
Add possibility to make a custom directories list instead of relying on WinExplorer or DOpus

### ISSUE THREAD

**Issue by Lebon14** [ThioJoe/AHK-Scripts#4]
Hey. Thanks for sharing this tool. I just finished watching the video.

You know, I'd love to see a function where I can enumerate the folders I want to go to instead of having to basically predict what my favorites will be by opening tabs in DOpus (that's what I use as well).

Of course, somebody could just disable that list if they don't want to.

Cheers.

**Comment by Joaqarq** [comment]
yes!! it would be great if i could have a custom "favourites" list of my most used directories pinned at the top!

**Comment by ThioJoe** [comment]
Yea a favorites list is something I plan to add. Probably conditional favorites too. I'm making a list of planned stuff on the wiki page.

**Comment by FlexXx1212** [comment]
I added this feature in my pull request
https://github.com/ThioJoe/AHK-Scripts/pull/18

**Comment by ThioJoe** [comment]
Version 1.2.0 now has the ability to add a custom favorites list and a conditional favorites feature.
