### ISSUE TITLE
Windows 10 friendly option

### ISSUE THREAD

**Issue by robbely** [ThioJoe/AHK-Scripts#5]
Could you add an option to list just the folders (ie without the window's name for each folder)? Windows 10 doesn't have explorer tabs so each entry is interleaved with "Explorer Window 1", "Explorer Window 2"...etc making it harder to find the path you are looking for.

**Comment by ThioJoe** [comment]
Hm yea I hadn't considered that, I'll try to add that when I have time, next couple days are busy though

**Comment by ThioJoe** [comment]
Version 1.2.0 now has a setting to not group windows explorer paths

**Comment by robbely** [comment]
Perfect :)
Many thanks for the quick fix
